import React from 'react';
import Layout from './components/Layout';
import Home from './pages/Home';

// The React app now ONLY serves the homepage. 
// All other pages (Privacy, Blog, etc.) are pure, static HTML files 
// generated by generate-static.mjs for maximum AdSense compatibility.
export default function App() {
  return (
    <Layout>
      <Home />
    </Layout>
  );
}
